language: python
python:
  - "3.6"
env:
  - PYTHONPATH=hgw_common/
before_install:
  pip install Django==1.11.7 mock==2.0.0 djangorestframework==3.8.2 django-oauth-toolkit==0.12.0 django-cors-middleware==1.3.1 \
  requests==2.18.4 requests_oauthlib==0.8.0 kafka_python==1.3.5 pycryptodomex==3.4.7 coreapi==2.3.3 drf_yasg PyYAML==5.1.1 \
  django-webpack-loader==0.6.0 djangosaml2==0.16.10
script: 
  - python consent_manager/manage.py test consent_manager/test/unit/
  - python hgw_frontend/manage.py test hgw_frontend/test
  - python hgw_backend/manage.py test hgw_backend/test
  - python hgw_common/hgw_common/manage.py test hgw_common/hgw_common/test/unit/
  - cd hgw_dispatcher
  - python -m unittest test
branches:
  only:
    - develop
