language: python
python:
  - "3.6"
before_install:
  pip install -r hgw_frontend/requirements.txt
script: 
  - python consent_manager/manage.py test consent_manager/test/
  - python hgw_frontend/manage.py test hgw_frontend/test
  - python hgw_backend/manage.py test hgw_backend/test
  - python hgw_common/hgw_common/manage.py test hgw_common/hgw_common/test
  - cd hgw_dispatcher
  - python -m unittest test
branches:
  only:
    - develop
