django:
  debug: true
  secret_key: i*w3i*-y589ynfl_sar!h9r1mpra8mkjpwobeage5h5a(0x!d$
  hostname: consentmanager
  port: 8002
  timezone: Europe/Rome
  database:
    name: ../consent_manager_db.sqlite3

saml:
  service: ts_cns
  idp_url: https://tscns/idp/shibboleth
  sp_name: Consent Manager Service Provider
  sp_cert: ../saml2/spid.cert.pem
  sp_key: ../saml2/spid.key.pem
