django:
  debug: true
  secret_key: i*w3i*-y589ynfl_sar!h9r1mpra8mkjpwobeage5h5a(0x!d$
  hostname: consentmanager
  port: 8002
  timezone: Europe/Rome
  database:
    name: ../consent_manager_db.sqlite3

saml:
  service: tscns
  idp_url: https://tscns/idp/shibboleth
  sp_name: Consent Manager Service Provider
  sp_cert: ../saml2/saml2.cert.pem
  sp_key: ../saml2/saml2.key.pem

kafka:
  uri: kafka:9093
  ssl: true
  ca_cert: ../../certs/ca/kafka/certs/ca/kafka.chain.cert.pem
  client_cert: ../../certs/ca/kafka/certs/consentmanager/cert.pem
  client_key: ../../certs/ca/kafka/certs/consentmanager/key.pem