version: '3.0'
services:
  hgw_frontend:
    image: crs4/hgw_frontend:latest
    ports:
      - 8000:8000
    volumes:
      - ./config_files/hgw_frontend_config.tscns.yml:/etc/hgw_service/hgw_frontend_config.yml
      - ../../../certs/ca/root/ca.cert.pem:/cacerts/ca.cert.pem
      - ../../../certs/ca/web/certs/ca/web.cert.pem:/cacerts/web.cert.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.cert.pem:/cacerts/kafka.cert.pem
      - ../../../certs/ca/web/certs/hgwfrontend:/container/web_certs/
      - ../../../certs/ca/kafka/certs/hgwfrontend/cert.pem:/container/client_certs/cert.pem
      - ../../../certs/ca/kafka/certs/hgwfrontend/key.pem:/container/client_certs/key.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.chain.cert.pem:/container/client_certs/kafka.chain.cert.pem
      - ../../../certs/:/container/certs/
    networks:
      default:
        aliases:
          - hgwfrontend

  hgw_backend:
    image: crs4/hgw_backend:latest
    depends_on:
      - kafka
    entrypoint: ["/custom_entrypoint/wait-for-it.sh", "kafka:9093", "--", "/docker-entrypoint.sh"]
    environment:
      - TZ=CET
    ports:
      - 8003:8003
    volumes:
      - ./config_files/hgw_backend_config.yml:/etc/hgw_service/hgw_backend_config.yml
      - ../../../certs/ca/root/ca.cert.pem:/cacerts/ca.cert.pem
      - ../../../certs/ca/web/certs/ca/web.cert.pem:/cacerts/web.cert.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.cert.pem:/cacerts/kafka.cert.pem
      - ../../../certs/ca/web/certs/hgwbackend/:/container/web_certs/
      - ../../../certs/ca/kafka/certs/hgwbackend/cert.pem:/container/client_certs/cert.pem
      - ../../../certs/ca/kafka/certs/hgwbackend/key.pem:/container/client_certs/key.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.chain.cert.pem:/container/client_certs/kafka.chain.cert.pem
      - ../../../certs/ca/web/certs/hgwbackend/source_endpoint_mockup_client.cert.pem:/container/service/media/source_endpoint_mockup_client.cert.pem
      - ../../../certs/ca/web/certs/hgwbackend/source_endpoint_mockup_client.key.pem:/container/service/media/source_endpoint_mockup_client.key.pem
    networks:
      default:
        aliases:
          - hgwbackend

  consent_manager:
    image: crs4/consent_manager:latest
    environment:
      - TZ=CET
    ports:
      - 8002:8002
    volumes:
      - ./config_files/consent_manager_config.tscns.yml:/etc/hgw_service/consent_manager_config.yml
      - ../../../certs/ca/root/ca.cert.pem:/cacerts/ca.cert.pem
      - ../../../certs/ca/web/certs/ca/web.cert.pem:/cacerts/web.cert.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.cert.pem:/cacerts/kafka.cert.pem
      - ../../../certs/ca/web/certs/consentmanager/:/container/web_certs/
    networks:
      default:
        aliases:
          - consentmanager

  kafka:
    image: crs4/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_PORT=9092
      - KAFKA_SSL_PORT=9093
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=channel_notification:1:1:hgwfrontend:hgwbackend
      - TZ=CET
    extra_hosts:
      - "kafka:127.0.1.1"
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ../../../certs/ca/kafka/certs/kafka-server/:/container/certs/
    networks:
      default:
        aliases:
          - kafka

  hgw_dispatcher:
    image: crs4/hgw_dispatcher:latest
    depends_on:
      - kafka
      - consent_manager
    volumes:
      - ./config_files/hgw_dispatcher_config.yml:/etc/hgw_service/hgw_dispatcher_config.yml
      - ../../../certs/ca/root/ca.cert.pem:/cacerts/ca.cert.pem
      - ../../../certs/ca/web/certs/ca/web.cert.pem:/cacerts/web.cert.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.cert.pem:/cacerts/kafka.cert.pem
      - ../../../certs/ca/kafka/certs/hgwdispatcher/cert.pem:/container/client_certs/cert.pem
      - ../../../certs/ca/kafka/certs/hgwdispatcher/key.pem:/container/client_certs/key.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.chain.cert.pem:/container/client_certs/kafka.chain.cert.pem
    entrypoint: ["/custom_entrypoint/wait-for-it.sh", "kafka:9093", "--",
      "/custom_entrypoint/wait-for-it.sh", "consentmanager:8002", "--",
      "/custom_entrypoint/wait-for-it.sh", "hgwbackend:8003", "--", "/docker-entrypoint.sh"]