version: '3.0'
services:
  spid-testenv-identityserver:
    build: ../../images/common/spid_testenv_identityserver/
    image: crs4/spid-testenv-identityserver
    ports:
      - "9443:9443"
    extra_hosts:
      - "spid-testenv-identityserver:127.0.1.1"
    networks:
      default:
        aliases:
          - spid-testenv-identityserver

  spid-testenv-backoffice:
    build: ../../images/common/spid_testenv_backoffice/
    image: crs4/spid-testenv-backoffice
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - spid-testenv-identityserver
    networks:
      default:
        aliases:
          - spid-testenv-backoffice

  hgw_frontend:
    build:
      context: ../../images/production/hgw_frontend
      args:
        HTTP_PORT: 8000
    image: crs4/hgw_frontend:production
    ports:
      - 8000:8000
    networks:
      default:
        aliases:
          - hgwfrontend

  hgw_backend:
    build:
      context: ../../images/production/hgw_backend
    image: crs4/hgw_backend:production
    depends_on:
      - kafka
    entrypoint: ["/container/wait-for-it.sh", "kafka:9093", "--", "/container/custom-docker-entrypoint.sh"]
    environment:
      - TZ=CET
    ports:
      - 8003:8003
    networks:
      default:
        aliases:
          - hgwbackend

  consent_manager:
    build:
      context: ../../images/production/consent_manager
    image: crs4/consent_manager:production
    environment:
      - TZ=CET
    ports:
      - 8002:8002
    networks:
      default:
        aliases:
          - consentmanager

  kafka:
    build: ../../images/production/kafka
    image: crs4/kafka:production
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_PORT=9092
      - KAFKA_SSL_PORT=9093
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - TZ=CET
    extra_hosts:
      - "kafka:127.0.1.1"
    ports:
      - 9092:9092
      - 9093:9093
    networks:
      default:
        aliases:
          - kafka

  hgw_dispatcher:
    build: ../../images/production/hgw_dispatcher
    image: crs4/hgw_dispatcher:production
    depends_on:
      - kafka
      - consent_manager
    entrypoint: ["/wait-for-it.sh", "kafka:9093", "--", "/wait-for-it.sh", "consent_manager:8002", "--",
      "/wait-for-it.sh", "hgw_backend:8003", "--", "/launch-dispatcher.sh"]