version: '3.0'
services:
  spid-testenv-identityserver:
    image: crs4/spid-testenv-identityserver:latest
    ports:
      - "9443:9443"
    extra_hosts:
      - "spid-testenv-identityserver:127.0.1.1"
    networks:
      default:
        aliases:
          - spid-testenv-identityserver

  spid-testenv-backoffice:
    image: crs4/spid-testenv-backoffice:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - spid-testenv-identityserver
    networks:
      default:
        aliases:
          - spid-testenv-backoffice