version: '3.0'
services:
  ts_cns_mysql:
    build: ../../images/common/ts_cns_mysql
    image: crs4/ts_cns_mysql
    ports:
      - 3306:3306
    environment:
      - TZ=CET
      - MYSQL_ROOT_PASSWORD=shibboleth

  ts_cns_shibboleth:
    build: ../../images/common/ts_cns_shibboleth
    image: crs4/ts_cns_shibboleth
    ports:
      - 443:443
    environment:
      - TZ=CET
      - DEVELOPMENT=true
      - SERVER_NAME=tscns
    networks:
      default:
        aliases:
          - tscns

