version: '3.0'
services:
  ts_cns_mysql:
    build: ../../images/common/ts_cns_mysql
    image: crs4/ts_cns_mysql
    ports:
      - 3306:3306
    environment:
      - TZ=CET
      - MYSQL_ROOT_PASSWORD=shibboleth
    networks:
      default:
        aliases:
          - mysql.healthgateway.it

  ts_cns_shibboleth:
    build: ../../images/common/ts_cns_shibboleth
    image: crs4/ts_cns_shibboleth
    extra_hosts:
      - "fakespid.healthgateway.it:127.0.1.1"
    ports:
      - 443:443
    environment:
      - TZ=CET
      - DEVELOPMENT=true
    networks:
      default:
        aliases:
          - fakespid.healthgateway.it

